### ISSUE TITLE
TP1

### ISSUE THREAD

**Issue by Laski** [gfourcade/cienciadatos#1]
Hola! Podemos usar issues para comunicarnos y trackear las tareas :stuck_out_tongue: .
Hoy hablé un toque al final con DFS. Lo de la varianza que puse al final está mal: puede haber un escenario en donde por ejemplo los atletas van llegando en orden de velocidad, con una diferencia de medio segundo entre cada uno, pero en una carrera de cuatro horas. Eso tiene varianza casi cero, pero los datos son mega dependientes de los atletas.

Dijo que el testeo de independencia se puede hacer tirando una correlación entre las velocidades de los atletas en días de sol con la de los atletas en días de lluvia. La hipótesis nula sería que el más rápido en días de sol lo es también en días de lluvia. Si no hay correlación, entonces se puede hipotetizar que en días de lluvia la velocidad es independiente del atleta. Bastante parecido a lo que habíamos concluido, creo, pero sin que haga falta reordenar nada.

**Comment by gushuro** [comment]
Tiene sentido.
Lo último no sé si me cierra, o si entendí bien tu idea. Cómo correlacionás al más rápido con todos los demás?
Prefiero reordenar :P

**Comment by Laski** [comment]
No correlacionás al más rápido con los demás. Vos tenés una lista de tiempos en días de sol `x` y días de lluvia `y`. Como cada fila corresponde al mismo atleta, podés calcular la correlación entre `x` e `y` y si eso te da mal, medio que alcanza para decir que no depende del atleta.

**Comment by Laski** [comment]
Y para comparar, podés correlacionar `x` con `z` (tiempos en días nublados) y va a dar re alto, porque en días nublados la velocidad sí depende del atleta.

**Comment by Laski** [comment]
TODO:
- Agregar recta en los gráficos de correlación.
- Poner etiquetas en todos los ejes.

**Comment by Laski** [comment]
- Conclusiones

**Comment by gfourcade** [comment]
Hice 
-    Agregar recta en los gráficos de correlación.
-    Poner etiquetas en todos los ejes.

Faltarían unas conclusiones.

**Comment by Laski** [comment]
Cierro hasta que la corrección nos diga qué debemos hacer.
